[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    minify = true
    # Это ключевая опция для уменьшения размера функций
    includeFiles = []
    # Не включать никаких дополнительных файлов, которые не требуются

[functions]
  # Убираем лишние файлы, которые увеличивают размер
  included_files = []
  node_bundler = "esbuild"